config/routes.rb
Rails.application.routes.draw do

  root :to => 'users#index'
  resources :users
  resources :categories

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
    end
  end

  devise_for :admins, only: :sessions
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_paranoid
  belongs_to :category

  validates :category_id, :name, :tel, :address, presence: true
  validates :tel, uniqueness: true

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController

  def index
    @users =  User.joins(:category).order('categories.lft, users.updated_at desc').page(params[:page]).per(20)
  end

  def show
    @user = User.where(id: params[:id]).first
    @message = @user.present? ? '' : "找不到该员工"
  end

end

app/controllers/users_controller.rb
class UsersController < BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def index
    @users = User.joins(:category).order('categories.lft, users.updated_at desc').page(params[:page]).per(20)
  end

  def new
    @user = User.new
  end

  def show

  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to (user_path @user), notice: '创建成功' }
      else
        format.html { render :new }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @user.update user_params
        format.html { redirect_to (user_path @user), notice: '修改成功' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: '删除成功' }
    end
  end


  private

  def set_user
    @user = User.find_by_id params[:id].to_i
    unless @user.present?
      respond_to do |format|
        format.html {redirect_to users_path, error: "找不到该用户"}
      end
    end
  end

  def user_params
    params.require(:user).permit(:name, :tel, :address, :category_id)
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form_content">
  <%= f.label :category_id, raw("组织#{get_fill}") %>

  <%= f.select :category_id, nested_set_options(Category, @user.category) {|i| "#{'-' * i.level} #{i.name}" }, {selected: @user.category_id, include_blank: true},  class: "form-control" %>

  <%= f.label :name, raw("姓名#{get_fill}") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :tel, raw("电话号码#{get_fill}")  %>
  <%= f.text_field :tel, class: "form-control"%>

  <%= f.label :address, raw("地址#{get_fill}")  %>
  <%= f.text_field :address, class: "form-control"%>
</div>
<%= f.submit "提交", class: "btn btn-primary" %>

app/views/users/edit.html.erb
<%= error_messages_for :user%>
<div class="row">
  <div class="col-sm-5">
    <%= form_for @user, url: user_path do |f| %>
        <%= render partial: 'users/form', locals: {f: f} %>

    <% end %>
  </div>
  <div class="col-sm-4">
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-sm-8">
    <table class="table">
      <div class="row">
        <div class="col-sm-6" align="left">员工列表</div>
        <div class="col-sm-6" align="right"><%= link_to '新建员工', new_user_path %></div>
      </div>
      <tbody>
      <% @users.each do |user| %>
          <tr>
            <td><%= link_to "#{'-' * user.category.level} #{user.category.name}", category_path(user.category) %></td>
            <td><%= link_to user.name, user_path(user) %></td>
            <td><%= user.tel %></td>
            <td><%= user.address %></td>
            <td><%= link_to '编辑', edit_user_path(user) %></td>
            <td><%= link_to '删除', user_path(user), method: :delete %></td>
            <td><%= user.created_at.to_s(:db) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= paginate @users, :params => params%>
  </div>

</div>

app/views/users/new.html.erb
<%= error_messages_for :user%>
<div class="row">
  <div class="col-sm-5">
    <%= form_for @user, url: users_path do |f| %>
        <%= render partial: 'users/form', locals: {f: f} %>

    <% end %>
  </div>
  <div class="col-sm-4">
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-6">
    <table class="table">
      <div class="row">
        <div class="col-sm-4" align="left">员工信息</div>
      </div>
      <tbody>
          <tr>
            <th>组织:</th>
            <td><%= @user.category.try(:name) %></td>
          </tr>
          <tr>
            <th>姓名:</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>电话号码:</th>
            <td><%= @user.tel %></td>
          </tr>
          <tr>
            <th>地址:</th>
            <td><%= @user.address %></td>
          </tr>
      </tbody>
    </table>
    <div class="center">
      <%= link_to(users_path, class: 'btn btn-small btn') do%>
          <i class="icon-on-left icon-arrow-left"></i>
          回到一览
          <i class="icon-undo bigger-150 middle"></i>
      <% end %>
    </div>
  </div>

</div>