config/routes.rb
Rails.application.routes.draw do

  root :to => 'users#index'
  resources :users
  resources :categories

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
    end
  end

  devise_for :admins, only: :sessions
end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_paranoid
  acts_as_nested_set
  validates :name, presence: true
  has_many :users
end

app/controllers/categories_controller.rb
class CategoriesController < BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.order(:lft)
  end

  def new
    @category = Category.new
  end

  def show

  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to (category_path @category), notice: '创建成功' }
      else
        format.html { render :new }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @category.update category_params
        format.html { redirect_to (category_path @category), notice: '修改成功' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    if !@category.leaf?
      respond_to do |format|
        flash[:error] = '请先删除子组织'
        format.html { redirect_to categories_path}
      end
    elsif User.where(category_id: @category.id).present?
      flash[:error] = '有员工从属于该组织'
      format.html { redirect_to categories_path}
    else
      @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_path, notice: '删除成功' }
      end
    end

  end


  private

  def set_category
    @category = Category.find_by_id params[:id].to_i
    unless @category.present?
      respond_to do |format|
        format.html {redirect_to categories_path, error: "找不到该组织"}
      end
    end
  end

  def category_params
    params.require(:category).permit(:name, :parent_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="form_content">
  <%= f.label :parent_id, "上级组织名" %>

  <%= f.select :parent_id, nested_set_options(Category, @category) {|i| "#{'-' * i.level} #{i.try(:name)}"}, {include_blank: true},  class: "form-control" %>

  <%= f.label :name, raw("组织名#{get_fill}") %>
  <%= f.text_field :name, class: "form-control" %>

</div>
<%= f.submit "提交", class: "btn btn-primary" %>

app/views/categories/edit.html.erb
<%= error_messages_for :user%>
<div class="row">
  <div class="col-sm-5">
    <%= form_for @category, url: category_path do |f| %>
        <%= render partial: 'categories/form', locals: {f: f} %>

    <% end %>
  </div>
  <div class="col-sm-4">
  </div>
</div>

app/views/categories/index.html.erb
<div class="row">
  <div class="col-sm-8">
    <table class="table">
      <div class="row">
        <div class="col-sm-6" align="left">组织架构列表</div>
        <div class="col-sm-6" align="right"><%= link_to '新建组织', new_category_path %></div>
      </div>
      <tbody>
      <% @categories.each do |category| %>
              <tr>
                <td><%= link_to "#{'-' * category.level} #{category.name}" , category_path(category) %></td>
                <td><%= link_to '编辑', edit_category_path(category) %></td>
                <td><%= link_to '删除', category_path(category), method: :delete %></td>
                <td><%= category.created_at.to_s(:db) %></td>
              </tr>

      <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/categories/new.html.erb
<%= error_messages_for :category%>
<div class="row">
  <div class="col-sm-5">
    <%= form_for @category, url: categories_path do |f| %>
        <%= render partial: 'categories/form', locals: {f: f} %>

    <% end %>
  </div>
  <div class="col-sm-4">
  </div>
</div>

app/views/categories/show.html.erb
<div class="row">
  <div class="col-sm-6">
    <table class="table">
      <div class="row">
        <div class="col-sm-4" align="left">员工信息</div>
      </div>
      <tbody>
          <tr>
            <th>上级组织名:</th>
            <td><%= @category.parent.try(:name) %></td>
          </tr>
          <tr>
            <th>组织名:</th>
            <td><%= @category.name %></td>
          </tr>
      </tbody>
    </table>
    <div class="center">
      <%= link_to(categories_path, class: 'btn btn-small btn') do%>
          <i class="icon-on-left icon-arrow-left"></i>
          回到一览
          <i class="icon-undo bigger-150 middle"></i>
      <% end %>
    </div>
  </div>

</div>